name: enhanced_url_launcher_web
description: Web platform implementation of enhanced_url_launcher for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/masewo/enhanced_url_launcher/tree/master/enhanced_url_launcher_web
issue_tracker: https://github.com/masewo/enhanced_url_launcher/issues
version: 2.0.18

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: enhanced_url_launcher
    platforms:
      web:
        pluginClass: EnhancedUrlLauncherPlugin
        fileName: enhanced_url_launcher_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  enhanced_url_launcher_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
