name: enhanced_url_launcher_platform_interface
description: A common platform interface for the enhanced_url_launcher plugin for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/masewo/enhanced_url_launcher/tree/master/enhanced_url_launcher_platform_interface
issue_tracker: https://github.com/masewo/enhanced_url_launcher/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.1.2

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
