name: enhanced_url_launcher_windows
description: Windows implementation of the enhanced_url_launcher plugin  for launching a URL. Supports
  web, phone, SMS, and email schemes. for launching a URL.
repository: https://github.com/masewo/enhanced_url_launcher/tree/master/enhanced_url_launcher_windows
issue_tracker: https://github.com/masewo/enhanced_url_launcher/issues
version: 3.0.8

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: enhanced_url_launcher
    platforms:
      windows:
        pluginClass: UrlLauncherWindows
        dartPluginClass: UrlLauncherWindows

dependencies:
  flutter:
    sdk: flutter
  enhanced_url_launcher_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^5.0.1
  test: ^1.16.3
