name: enhanced_url_launcher_android
description: Android implementation of the enhanced_url_launcher plugin  for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/masewo/enhanced_url_launcher/tree/master/enhanced_url_launcher_android
issue_tracker: https://github.com/masewo/enhanced_url_launcher/issues
version: 6.0.34

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: enhanced_url_launcher
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: EnhancedUrlLauncherPlugin
        dartPluginClass: UrlLauncherAndroid

dependencies:
  flutter:
    sdk: flutter
  enhanced_url_launcher_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3
