name: enhanced_url_launcher_linux
description: Linux implementation of the enhanced_url_launcher plugin  for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/masewo/enhanced_url_launcher/tree/master/enhanced_url_launcher_linux
issue_tracker: https://github.com/masewo/enhanced_url_launcher/issues
version: 3.0.6

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: enhanced_url_launcher
    platforms:
      linux:
        pluginClass: EnhancedUrlLauncherPlugin
        dartPluginClass: UrlLauncherLinux

dependencies:
  flutter:
    sdk: flutter
  enhanced_url_launcher_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3
